import asyncio
import os
import time
from playwright.async_api import async_playwright
import vertexai
from vertexai.generative_models import GenerativeModel, Part

# Configuration
OUT_DIR = "/home/james/SovereignOS/scratch/fanstack_screenshots"
REPORT_PATH = "/home/james/sovereign_inbox/today/FanStack_Vertex_Deep_Crawl.md"
BASE_URL = "https://127.0.0.1:3009"
CREDENTIALS_PATH = "/home/james/SovereignOS/config/vertex_sa.json"
PROJECT_ID = "gen-lang-client-0840454416"
LOCATION = "us-central1"
MODEL_NAME = "gemini-2.5-flash"

ROOMS = [
    "playcall_desk", 
    "live_chat_sniper", 
    "persona_center", 
    "hot_takes", 
    "highlight_heist", 
    "god_mode"
]

def analyze_image_with_vertex(image_path: str, room_name: str) -> str:
    print(f"[{room_name}] Analyzing with Vertex AI...")
    try:
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = CREDENTIALS_PATH
        vertexai.init(project=PROJECT_ID, location=LOCATION)
        model = GenerativeModel(MODEL_NAME)
        
        with open(image_path, "rb") as f:
            image_data = f.read()
        
        image_part = Part.from_data(data=image_data, mime_type="image/png")
        
        prompt = f"""
You are an expert product analyst and technical evaluator. 
Analyze this screenshot of the '{room_name}' module from the Sovereign FanStack application.
Write a detailed 'pitch deck' style capability analysis for this specific module.
Include:
- The core purpose of the module.
- Key features visible in the UI.
- How an Admin or Operator would use this in a live sports broadcast scenario.

Keep the tone professional, investor-ready, and analytical.
"""
        response = model.generate_content([image_part, prompt])
        parts_text = []
        if response and response.candidates and len(response.candidates) > 0:
            candidate = response.candidates[0]
            if candidate.content and candidate.content.parts:
                for part in candidate.content.parts:
                    if hasattr(part, "text") and part.text:
                        parts_text.append(part.text)
        if parts_text:
            return "".join(parts_text)
        try:
            return response.text
        except Exception:
            return "Empty response from Vertex AI"
    except Exception as e:
        return f"Error analyzing {room_name}: {e}"

async def run_crawl():
    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    
    report_content = "# Sovereign FanStack: Vertex AI Deep Crawl Report\n\n"
    report_content += "This automated report was generated by Vertex AI (`gemini-2.5-flash`) crawling the FanStack live interfaces.\n\n"
    
    print("Launching headless browser...")
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=['--ignore-certificate-errors'])
        context = await browser.new_context(
            viewport={'width': 1920, 'height': 1080},
            ignore_https_errors=True
        )
        await context.add_init_script("window.localStorage.setItem('sov_auth', 'unlocked');")
        page = await context.new_page()
        
        for room in ROOMS:
            print(f"Navigating to {room}...")
            url = f"{BASE_URL}/?vip=creator&room={room}"
            await page.goto(url, wait_until="networkidle")
            
            # Wait a moment for dynamic data/components to render
            await page.wait_for_timeout(3000)
            
            image_path = os.path.join(OUT_DIR, f"{room}.png")
            await page.screenshot(path=image_path, full_page=True)
            print(f"Saved screenshot: {image_path}")
            
            # Analyze with Vertex
            analysis = analyze_image_with_vertex(image_path, room)
            
            # Append to report
            report_content += f"## Module: `{room}`\n\n"
            report_content += f"![{room} screenshot]({image_path})\n\n"
            report_content += f"### Vertex AI Analysis\n"
            report_content += f"{analysis}\n\n"
            report_content += "---\n\n"
            
        await browser.close()
        
    print(f"Writing report to {REPORT_PATH}...")
    with open(REPORT_PATH, "w") as f:
        f.write(report_content)
    print("Deep crawl complete!")

if __name__ == "__main__":
    asyncio.run(run_crawl())
